on: [push, pull_request]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    -   php: '7.4'
                    -   php: '8.0'
                    -   php: '8.1'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: phpstan, cs2pr

            -   name: Setup problem matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist

            -   name: Run phpunit
                run: vendor/bin/phpunit

            -   name: Run phpcs
                run: vendor/bin/php-cs-fixer fix --dry-run | cs2pr

            -   name: Run PHPStan
                run: phpstan analyse src
